[package]
name = "youtube-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.18"
crossterm = "0.23"
invidious = "0.2"
futures = "0.3"
hrtime = "0.2"
home = "0.5"
reqwest = {version = "0.11", features = ["blocking"]}
tokio = { version = "1.18", features = ["full"] }
viuer = "0.6"
thousands = "0.2"
chrono = "0.4"
serde = "1"
serde_yaml = "0.8"
serde_json = "1"

[profile.dev.package."*"]
opt-level = 3
