[package]
name = "youtube-tui"
version = "0.5.0"
edition = "2021"
authors = ["Siriusmart <siriusmart@tuta.io>"]
description = "An aesthetically pleasing YouTube TUI written in Rust"
readme = "README.md"
license = "GPL-3.0"
keywords = ["cli", "terminal", "youtube", "tui"]
categories =["command-line-interface", "command-line-utilities"]
repository = "https://github.com/Siriusmart/youtube-tui"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0", features = ["derive"]}
tui = {version = "0.19", features = ["serde"]}
crossterm = {version = "0.25", features = ["serde"]}
viuer = {version = "0.6", features = ["sixel"]}
home = "0.5"
chrono = {version = "0.4", default-features = false, features = ["clock"]}
# tui-additions = {version = "0.1", default-features = false, features = ["framework", "widgets"]}
typemap = "0.3"
invidious = {version = "0.3", default-features = false, features = ["reqwest"]}
serde_yaml = "0.9"
dyn-clone = "1.0"
tokio = "1.21"
futures = "0.3"
reqwest = "0.11"
# serde_json = "1.0"
tui-additions = {path = "../../Rust/Packages/tui-additions", default-features = false, features = ["framework", "widgets"]}
