[package]
name = "youtube-tui"
version = "0.7.0"
authors = ["Siriusmart <siriusmart@tuta.io>"]
edition = "2021"
description = "An aesthetically pleasing YouTube TUI written in Rust"
documentation = "https://docs.rs/youtube-tui"
readme = "README.md"
homepage = "https://siriusmart.github.io/youtube-tui"
repository = "https://github.com/siriusmart/youtube-tui"
license = "GPL-3.0-or-later"
keywords = ["cli", "terminal", "youtube", "tui"]
categories =["command-line-interface", "command-line-utilities"]
exclude = ["/docs", "/LICENSE"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["sixel", "halfblock", "clipboard"]
sixel = ["viuer/sixel"]
halfblock = ["viuer"]
clipboard = ["dep:clipboard"]

[dependencies]
serde = {version = "1.0", default-features = false, features = ["derive"]}
tui = {version = "0.19", default-features = false, features = ["serde"]}
crossterm = {version = "0.26", default-features = false, features = ["serde"]}
viuer = {version = "0.6", default-features = false, optional = true}
home = "0.5"
chrono = {version = "0.4", default-features = false, features = ["clock"]}
typemap = {version = "0.3", default-features = false}
tui-additions = {version = "0.1.13", default-features = false, features = ["framework", "widgets"]}
invidious = {version = "0.4", default-features = false, features = ["reqwest"]}
serde_yaml = {version = "0.9", default-features = false}
dyn-clone = {version = "1.0", default-features = false}
tokio = {version = "1.21", default-features = false}
futures = {version = "0.3", default-features = false}
reqwest = {version = "0.11", default-features = false}
serde_json = {version = "1.0", default-features = false}
clipboard = {version = "0.5", optional = true}

# tui-additions = {path = "../../Rust/Packages/tui-additions", default-features = false, features = ["framework", "widgets"]}
# invidious = {path = "../../Rust/Packages/invidious", default-features = false, features = ["reqwest"]}
